language: node_js
node_js:
- "4"
install:
- npm install
script:
- npm run lint
- npm test
after_success:
  deploy:
    skip_cleanup: true
    provider: heroku
    api_key:
      secure: "cf7e4d97-bb27-4606-ad29-db6f45c01059"
    on: master
    app: team2
