sudo: false
language: node_js
node_js:
- "4"
install:
- npm install
script:
- npm run lint
- npm test
after_success:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run deploy:static'
deploy:
    skip_cleanup: true
    provider: heroku
    api_key:
      secure: "Z5eKHxKZBJpYvJBkuXtMA8cIjcx3KqojX8n9jBdonf6gGJwUElm9g1HtnQFsXVo1GCq25d3QxF5nGK/JDmbPeiRM2JVLVn9dkuTxFL4v2iG5Mwy+g3amCf6wuRqPj6EbZsweypmxyPIuI6mf3hf4H0EM5vBYLFejFpIaA3HyJV+ytPzPeoBeVweu3baAiaueDfczLwf4domZEwPnsMdP0rKpFZusVCotatj3o/Mt3r+LIdLjaWDho8DdE25VU9u6rxRv+YyVEaItBm1vGSXOo2FkH3bdj/UlBwcf78Cp9Ir/uqttBOnLoJQAtR1p/FereyLzKf7ZnKNxfzKR15wnsN33xLEc8oZhTU6Ux1xwk6Yoqr7m4rniQOYyM1yPbEOqYQRecRZJ8bzddH/RocXjkIKVmxAWUvQ7TXMmOWNZjxXZ8oEE/R0hZxHT+QGf35ZP5ArvCe0ugr60Nkk40575iMnp9k5rdLBLEMKKN6cF7DrDViI81cNQ/Nd6UfA3biMqvxxkUiwu+mha68Ek2AQDoj0OAKH7DVFjJchpBo3vkigW5fVZjD70S18PPcotOJ07oyRQtl5oCy2Hu2rXEEYFleMgAkom9RmO6gb9Y1L57HD7UzJL0rCSdkkumUHIS8fcBqvgx+eyyRe6HvI2CP59dnCMU74Fss45QOjLXZ+SmUY="
    on: master
    app: team2
